### ISSUE TITLE
Generate signed bundle /apk

### ISSUE THREAD

**Issue by joshhazelhurst123** [peace-shillong/Hebrew-Interlinear-Old-Testament-Android#1]
Hi, I am trying to generate a signed bundle / apk to build. I have picked up some typos in the sqllite database and I would like to fix them. But as I attempt to build the apk. I encounter the errors below.

I am on a windows 8 android studio 3.3.1 sdk version: 26 
gradle: 4.10.1 
android plugin version: 3.3.1

Actionbar is now deprecated. Think that might have something to do with it. 

> Task :app:transformDexArchiveWithExternalLibsDexMergerForRelease FAILED
AGPBI: {"kind":"error","text":"Program type already present: android.support.v7.app.ActionBar$LayoutParams","sources":[{}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Program type already present: android.support.v7.app.ActionBar$LayoutParams
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
21 actionable tasks: 2 executed, 19 up-to-date

**Comment by joshhazelhurst123** [comment]
Help !!!

**Comment by peace-shillong** [comment]
Hello @joshhazelhurst123 Sorry for the late reply, 
I've been really busy this year on other projects and haven't touch this code,
If you have solved this, please let me know, 
I will look into it and hope to reply more sooner.
Thanks

**Comment by joshhazelhurst123** [comment]
Hi my friend,
I changed the SQL file and made the necessary changes where there was
errors, ie incorrect text. But as I then tried to update the apk file and
make it useable it would not compile. Think there is a reason why it would
not compile. I sent you the error messages. All I did was update the SQL
file and run the apk builder and it did not work.
Josh

**Comment by peace-shillong** [comment]
Hello @joshhazelhurst123 , I've fixed the bugs above and I was able to build and test the new APK and it's wroking fine.

I'm currently  on Android 3.4.2
and build gradle files with the following:

minSdkVersion 16
compileSdkVersion 28
buildToolsVersion "28.0.3"

gradle version 3.4.2

gradle-wrapper properties : 5.1.1

**Comment by peace-shillong** [comment]
@joshhazelhurst123 can you kindly share the sqlite database with new changes/typos fixed.
If you can also give a list of what words/letters you have changed in a list it would be really helpful.

**Comment by joshhazelhurst123** [comment]
Thank you

**Comment by joshhazelhurst123** [comment]
[ot.zip](https://github.com/peace-shillong/Hebrew-Interlinear-Old-Testament-Android/files/3807510/ot.zip)

**Comment by joshhazelhurst123** [comment]
bugs, psalm 21Fix, psalm 121:3Fix, ps1-8, proverbs 31:31 missing Fix, 
 ps22:16 fix, change screen navy blue, edit text
exodus.12

There was a message from a user on google play saying that the text was incorrect for the following verses above. I have changed the sql file. Check out google play messages and you will see. Let me know if that helps. Josh.

**Comment by peace-shillong** [comment]
Thanks, Josh, I will look into the sqlite db for now
I've read the reviews on google play, and found the following missing text:
1. some people said: the last verse of each book (is this true?), 39 verses are missing
2. Daniel chapter 12
3. Ps. 121:3  Mistake  
4. Proverbs 31:31 
5. In Hoses 14:1 the Yod is missing by the word Yisrael, the Hebrew letter?
6. Leviticus 27:34 is missing,
7. Missing: Malachi 4:6. Deuteronomy 34:12
8. Ps 1-8

I think we can work together and maybe have a new update for the app, 
I'm planning to have an option for the user to export the text in PDF (as seen in issue 2) 
Maybe when I'm done with this I will upload a new APP with your changes. 

If you can help out with the mistakes, it would be of great help.

**Comment by joshhazelhurst123** [comment]
Kyrshanlang R Dkhar, I am looking forward to working with you on this. Previously I opened up the sqlite database file and edited it that way. I can do this again for the verses above that you have mentioned. Could you build the apk file once I have completed that? Let me know if I am missing anything. 

I have uploaded the sqlite database above. ot.zip

Not sure how you are going to export the text to PDF. Would be interested how you do this. Could you have a brief description how you do this or a detailed one, up to you.

**Comment by peace-shillong** [comment]
OK Josh. I got the ot.zip database file. 
Yes, I can build the apk once you have completed and fixed a few more verses. Just send me the database later when you are done. 

(Q1. do you want me to rebuild the apk with the new database? I think it's best if we fix a few verses then we will build the apk)

By the way, you can call me peace (my nickname).

I've worked on a similar app on the Book of Revelation for my language (Khasi) with my relative, 
We have an option to export the entire chapter of the book to pdf.  So It will be similar, 
but I will have to check on how to display the verse. It will be tricky to do this in Hebrew with the Interlinear text, but once I'm done I can write a brief description of this.


> Kyrshanlang R Dkhar, I am looking forward to working with you on this. Previously I opened up the sqlite database file and edited it that way. I can do this again for the verses above that you have mentioned. Could you build the apk file once I have completed that? Let me know if I am missing anything.
> 
> I have uploaded the sqlite database above. ot.zip
> 
> Not sure how you are going to export the text to PDF. Would be interested how you do this. Could you have a brief description how you do this or a detailed one, up to you.

**Comment by joshhazelhurst123** [comment]
Hi Peace,
Thanks for your reply and for looking into this. I have gone through the
bullet points that you have mentioned. See below.

I am happy to start making changes to the database file now. This can be
included in the change log directory. Let me know if you have any
questions.
Josh

1). Not sure which ones are missing, I have updated the sql database.
I will double check for errors.
2). daniel 12:13 missing
13 “As for you, go your way till the end. You will rest, and then at the
end of the days you will rise to receive your allotted inheritance.”
3). Ps 121:3
I cannot see any mistakes here.
4). proverbs 31.31 missing
Honor her for all that her hands have done,
    and let her works bring her praise at the city gate.

5). Hosea 14:1
the yod is not missing

6). leviticus 27:34
These are the commands the LORD gave Moses at Mount Sinai for the
Israelites.

7). malachi 4:6
6 He will turn the hearts of the parents to their children, and the hearts
of the children to their parents; or else I will come and strike the land
with total destruction.”

7 continued). deuteronomy 34:12
For no one has ever shown the mighty power or performed the awesome deeds
that Moses did in the sight of all Israel.

8). Psalm 1-8
looks fine to me as I can see
