### ISSUE TITLE
Find app on Google play

### ISSUE THREAD

**Issue by Quebec83** [peace-shillong/Hebrew-Interlinear-Old-Testament-Android#2]
Hello, Can I find that app on Google Play? Also, since the content of the app is an e-book (interlinear hebrew bible), I was wondering if there was an easier way to print the book in a pdf. Thanks in advance,

Joel

**Comment by peace-shillong** [comment]
Yes, you can find it on Google Play: 
https://play.google.com/store/apps/details?id=stefankmitph.hiot&hl=en

**Comment by peace-shillong** [comment]
@Quebec83 The content is stored in SQLite Database, 
It could be possible to have an option in the app to export the data of a book into pdf, that would required some work tho.

**Comment by peace-shillong** [comment]
Hello @Quebec83 I'm working on this issue. 
Like I said the content Is stored in a database,  and the app displays it in a readable format. 

I've tried exporting the content directly to pdf  but the encoding doesn't match so I dont see hebrew text in the pdf but only ? And other characters.  

So I'm working on allowing users to share a verse as image and another feature where users can also export a verse as image.

**Comment by peace-shillong** [comment]
Hello @Quebec83 I've made changes to the app and we can now export and share the Hebrew Bible Verse from the app.
Here is the Google Play Store: 
https://play.google.com/store/apps/details?id=peace_shillong.hiot

Do give it a try. 
Cheers.
