### ISSUE TITLE
Is it possible to add hebrew audio that follows word by word?

### ISSUE THREAD

**Issue by elo884** [peace-shillong/Hebrew-Interlinear-Old-Testament-Android#6]
Hello, I have no idea what I'm doing and I wasn't sure where to post this. But is there a way to add audio to the app that follows along, word by word? Does anyone know how to do that? Would it be easy or hard? I'm learning Hebrew and it would be so helpful to follow along with the speaker if the app was pointing to the word he was on, even be able to slow down the audio? I know enough Hebrew to connect the audio and the word he's on but it would be helpful to have it integrated with the app. Anyway, I'm not sure if anyone will see this but thanks in advance for the response!

**Comment by peace-shillong** [comment]
![image](https://user-images.githubusercontent.com/33800152/80492013-15568680-8981-11ea-82bc-02f589d5614c.png)

There is an online website which lets you enter text in English and you can listen to both the English and Hebrew Text, I hope you find this useful.

This is the site with an example:
https://context.reverso.net/translation/english-hebrew/In+the+Beginning+God+created+the+heavens+and+the+Earth

You can enter your own text and do let me know how it is.
Thanks

**Comment by peace-shillong** [comment]
@elo884 Do check out the above-mentioned website. 
I will close this issue now.
